name: Unit tests

on:
  push:
    paths:
    - '.github/workflows/unit_tests.yml'
    - 'src/**'
    - 'tests/**'
    - 'package.json'
    - 'package-lock.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test
